-- 샘플
create table SAMPLE
(
    ID   NUMBER(24) generated by default on null as identity
        constraint PK_SAMPLE
            primary key,
    NAME VARCHAR2(255 char)
)
/


-- 유저
create table USERS
(
    CREATED_AT        TIMESTAMP(6)                           not null,
    CREATED_BY        VARCHAR2(50 char),
    EMAIL             VARCHAR2(50 char),
    ENTITY_STATUS     VARCHAR2(50 char) default 'ACTIVE'     not null,
    ID                NUMBER(24)        default "GFW"."ISEQ$$_110759".nextval generated by default on null as identity
		constraint PK_USERS
			primary key,
    NICKNAME          VARCHAR2(50 char)                      not null
        constraint UK_NICKNAME
            unique,
    PROVIDER          VARCHAR2(50 char)                      not null,
    PROVIDER_USERNAME VARCHAR2(30 char)                      not null,
    ROLE              VARCHAR2(50 char) default 'USER'       not null,
    TIME_ZONE         VARCHAR2(50 char) default 'Asia/Seoul' not null,
    UPDATED_AT        TIMESTAMP(6)                           not null,
    UPDATED_BY        VARCHAR2(50 char),
    constraint UK_PROVIDER_PROVIDER_USERNAME
        unique (PROVIDER, PROVIDER_USERNAME)
)
/

create trigger USERS_PROVIDER_ETRG
    before insert or update
    on USERS
    for each row
DECLARE
    v_val users.provider%TYPE; v_test users.provider%TYPE;
BEGIN
    v_val := 'APPLE'; v_test := TRIM(:new.provider);
    if v_test = '1' OR v_test = 'APPLE' THEN
        v_val := 'APPLE';
    elsif v_test = '2' OR v_test = 'KAKAO' THEN
        v_val := 'KAKAO';
    end if;
    :new.provider := v_val;
END;
/

create trigger USERS_ENTITY_STATUS_ETRG
    before insert or update
    on USERS
    for each row
DECLARE
    v_val users.entity_status%TYPE; v_test users.entity_status%TYPE;
BEGIN
    v_val := 'ACTIVE'; v_test := TRIM(:new.entity_status);
    if v_test = '1' OR v_test = 'ACTIVE' THEN
        v_val := 'ACTIVE';
    elsif v_test = '2' OR v_test = 'DELETED' THEN
        v_val := 'DELETED';
    end if;
    :new.entity_status := v_val;
END;
/

create trigger USERS_ROLE_ETRG
    before insert or update
    on USERS
    for each row
DECLARE
    v_val users.role%TYPE; v_test users.role%TYPE;
BEGIN
    v_val := 'ADMIN'; v_test := TRIM(:new.role);
    if v_test = '1' OR v_test = 'ADMIN' THEN
        v_val := 'ADMIN';
    elsif v_test = '2' OR v_test = 'USER' THEN
        v_val := 'USER';
    end if;
    :new.role := v_val;
END;
/



create trigger FOOTSTEP_ENTITY_STATUS_ETRG
    before insert or update
    on FOOTSTEP
    for each row
DECLARE
    v_val footstep.entity_status%TYPE; v_test footstep.entity_status%TYPE;
BEGIN
    v_val := 'ACTIVE'; v_test := TRIM(:new.entity_status);
    if v_test = '1' OR v_test = 'ACTIVE' THEN
        v_val := 'ACTIVE';
    elsif v_test = '2' OR v_test = 'DELETED' THEN
        v_val := 'DELETED';
    end if;
    :new.entity_status := v_val;
END;
/


-- 발자취
create table FOOTSTEP
(
    CONTENT       VARCHAR2(50 char),
    CREATED_AT    TIMESTAMP(6)      default SYSTIMESTAMP not null,
    DATE_         DATE                                   not null,
    ENTITY_STATUS VARCHAR2(50 char) default 'ACTIVE'     not null,
    ID            NUMBER(24)        default "GFW"."ISEQ$$_110751".nextval generated by default on null as identity
		constraint PK_FOOTSTEP
			primary key,
    IMAGE_URL     VARCHAR2(255 char)                     not null,
    UPDATED_AT    TIMESTAMP(6)      default SYSTIMESTAMP not null,
    USER_ID       NUMBER(24)                             not null
)
/

create trigger FOOTSTEP_ENTITY_STATUS_ETRG
    before insert or update
    on FOOTSTEP
    for each row
DECLARE
    v_val footstep.entity_status%TYPE; v_test footstep.entity_status%TYPE;
BEGIN
    v_val := 'ACTIVE'; v_test := TRIM(:new.entity_status);
    if v_test = '1' OR v_test = 'ACTIVE' THEN
        v_val := 'ACTIVE';
    elsif v_test = '2' OR v_test = 'DELETED' THEN
        v_val := 'DELETED';
    end if;
    :new.entity_status := v_val;
END;
/


