-- ===================================================================
-- 최종 최적화된 DDL (Optimized Final DDL)
-- 설명: 불필요한 시퀀스 기본값과 중복 트리거를 제거한 깔끔한 버전
-- ===================================================================

-- 테이블: SAMPLE
CREATE TABLE SAMPLE
(
    ID   NUMBER(24) GENERATED BY DEFAULT ON NULL AS IDENTITY,

    NAME VARCHAR2(255 CHAR),

    CONSTRAINT PK_SAMPLE PRIMARY KEY (ID)
);

-- 테이블: USERS
CREATE TABLE USERS
(
    ID                NUMBER(24) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ENTITY_STATUS     VARCHAR2(50 CHAR) DEFAULT 'ACTIVE'     NOT NULL,

    PROVIDER          VARCHAR2(50 CHAR)                      NOT NULL,
    PROVIDER_USERNAME VARCHAR2(30 CHAR)                      NOT NULL,
    EMAIL             VARCHAR2(50 CHAR),
    NICKNAME          VARCHAR2(50 CHAR)                      NOT NULL,
    ROLE              VARCHAR2(50 CHAR) DEFAULT 'USER'       NOT NULL,
    TIME_ZONE         VARCHAR2(50 CHAR) DEFAULT 'Asia/Seoul' NOT NULL,

    CREATED_AT        TIMESTAMP(6)                           NOT NULL,
    CREATED_BY        VARCHAR2(50 CHAR),
    UPDATED_AT        TIMESTAMP(6)                           NOT NULL,
    UPDATED_BY        VARCHAR2(50 CHAR),

    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT UK_PROVIDER_PROVIDER_USERNAME UNIQUE (PROVIDER, PROVIDER_USERNAME)
);

-- 테이블: FOOTSTEP
CREATE TABLE FOOTSTEP
(
    ID            NUMBER(24) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ENTITY_STATUS VARCHAR2(50 CHAR) DEFAULT 'ACTIVE'     NOT NULL,
    USER_ID       NUMBER(24)                             NOT NULL,

    ISSUE_DATE    DATE                                   NOT NULL, -- 'DATE' 예약어 이므로 ISSUE_DATE로 변경
    CONTENT       VARCHAR2(50 CHAR),
    IMAGE_URL     VARCHAR2(255 CHAR)                     NOT NULL,

    CREATED_AT    TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_FOOTSTEP PRIMARY KEY (ID)
);
